apiVersion: v1
kind: Service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: reverseproxy
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
